<?php require __DIR__ . '/_bootstrap.php';
$message = null; $erreur = null;
if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'ajouter') {
    $module = (int) ($_POST['idModule'] ?? 0); $titre = trim($_POST['titre'] ?? ''); $date = $_POST['dateLimite'] ?? '';
    $q = $db->prepare('SELECT idModule FROM module WHERE idModule=:module AND idFormateur=:formateur'); $q->execute(['module'=>$module,'formateur'=>$formateurId]);
    if (!$q->fetchColumn() || $titre === '' || $date === '') $erreur = 'Le module, le titre et la date limite sont obligatoires.';
    else { $q=$db->prepare('INSERT INTO evaluation (idModule,titre,dateLimite) VALUES (:module,:titre,:date)'); $q->execute(['module'=>$module,'titre'=>$titre,'date'=>$date]); journaliserAction('Création d’une évaluation',$titre); flashMessage('success','Évaluation ajoutée avec succès.'); header('Location: '.BASE_URL.'views/formateur/evaluations.php'); exit; }
}
if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'supprimer') { try { $q=$db->prepare('DELETE e FROM evaluation e INNER JOIN module m ON m.idModule=e.idModule WHERE e.idEvaluation=:evaluation AND m.idFormateur=:formateur'); $q->execute(['evaluation'=>(int)$_POST['idEvaluation'],'formateur'=>$formateurId]); journaliserAction('Suppression d’une évaluation','Évaluation #'.(int)$_POST['idEvaluation']); flashMessage('success','Évaluation supprimée.'); } catch (PDOException $exception) { flashMessage('error','Cette évaluation ne peut pas être supprimée car des résultats ou dépôts y sont rattachés.'); } header('Location: '.BASE_URL.'views/formateur/evaluations.php'); exit; }
$q=$db->prepare('SELECT e.*,m.libelle AS module FROM evaluation e INNER JOIN module m ON m.idModule=e.idModule WHERE m.idFormateur=:id ORDER BY e.dateLimite DESC'); $q->execute(['id'=>$formateurId]); $evaluations=$q->fetchAll(); $q=$db->prepare('SELECT idModule,libelle FROM module WHERE idFormateur=:id ORDER BY libelle'); $q->execute(['id'=>$formateurId]); $modules=$q->fetchAll(); $pageTitle='Évaluations'; $activeMenu='evaluations'; require __DIR__.'/../../includes/header.php'; ?>
<div class="card"><h2>Ajouter une évaluation</h2><?php if($erreur): ?><p style="color:#c62828"><?=htmlspecialchars($erreur)?></p><?php endif; ?><form method="post"><input type="hidden" name="action" value="ajouter"><select name="idModule" required><option value="">Module</option><?php foreach($modules as $module): ?><option value="<?=$module['idModule']?>"><?=htmlspecialchars($module['libelle'])?></option><?php endforeach; ?></select> <input name="titre" placeholder="Titre" required> <input type="datetime-local" name="dateLimite" required> <button class="btn" type="submit">Ajouter</button></form></div>
<div class="card"><h2>Mes évaluations</h2><table class="director-table"><thead><tr><th>Module</th><th>Titre</th><th>Date limite</th><th>Actions</th></tr></thead><tbody><?php foreach($evaluations as $evaluation): ?><tr><td><?=htmlspecialchars($evaluation['module'])?></td><td><?=htmlspecialchars($evaluation['titre'])?></td><td><?=htmlspecialchars($evaluation['dateLimite'])?></td><td><form method="post"><input type="hidden" name="action" value="supprimer"><input type="hidden" name="idEvaluation" value="<?=$evaluation['idEvaluation']?>"><button class="btn" style="background:#c62828" onclick="return confirm('Supprimer cette évaluation ?')">Supprimer</button></form></td></tr><?php endforeach; ?></tbody></table></div><?php require __DIR__.'/../../includes/footer.php'; ?>