<?php
require_once __DIR__ . '/../../controllers/helpers.php'; require_once __DIR__ . '/../../controllers/PaiementController.php';
requireRole(['comptable']); $controller = new PaiementController(); $idPaiement = (int) ($_GET['idPaiement'] ?? $_POST['idPaiement'] ?? 0); $paiement = $idPaiement ? $controller->getPaiementById($idPaiement) : null; $erreur = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $ok = $idPaiement ? $controller->modifierPaiement($idPaiement, $_POST['montant'] ?? 0, $_POST['modePaiement'] ?? '', trim($_POST['reference'] ?? '')) : $controller->enregistrerPaiement($_POST['montant'] ?? 0, $_POST['modePaiement'] ?? '', trim($_POST['reference'] ?? ''), (int) ($_POST['idInscription'] ?? 0));
    if ($ok) { header('Location: paiements_etudiants.php'); exit; } $erreur = 'Données invalides ou référence déjà utilisée.';
}
$inscriptions = (new PaiementController())->getInscriptionsValidees(); $pageTitle = $idPaiement ? 'Modifier un paiement' : 'Nouveau paiement'; $showSidebar = true; require __DIR__ . '/../../includes/header.php';
?>
<h1><?= htmlspecialchars($pageTitle) ?></h1><?php if ($erreur): ?><div class="card"><?= htmlspecialchars($erreur) ?></div><?php endif; ?><div class="card" style="max-width:560px"><form method="post"><?php if ($idPaiement): ?><input type="hidden" name="idPaiement" value="<?= $idPaiement ?>"><?php else: ?><label>Inscription<select name="idInscription" required><option value="">Sélectionner</option><?php foreach ($inscriptions as $inscription): ?><option value="<?= (int) $inscription['idInscription'] ?>"><?= htmlspecialchars($inscription['prenom'] . ' ' . $inscription['nom'] . ' - ' . $inscription['niveau_libelle']) ?></option><?php endforeach; ?></select></label><?php endif; ?><label>Montant<input type="number" name="montant" min="0.01" step="0.01" required value="<?= htmlspecialchars((string) ($paiement['montant'] ?? '')) ?>"></label><label>Mode<select name="modePaiement" required><?php foreach (['ESPECES','CHEQUE','VIREMENT','CARTE','MOBILE_MONEY'] as $mode): ?><option <?= (($paiement['modePaiement'] ?? '') === $mode) ? 'selected' : '' ?>><?= $mode ?></option><?php endforeach; ?></select></label><label>Référence<input name="reference" value="<?= htmlspecialchars((string) ($paiement['referencePaiement'] ?? '')) ?>"></label><button class="btn" type="submit">Enregistrer</button></form></div>
<?php require __DIR__ . '/../../includes/footer.php'; ?>